export const LOGIN_REQUEST = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_REQUEST = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGIN_FAILED";

export const GET_TABLE_DATA = "GET_TABLE_DATA";
export const GET_USERNAME = "GET_USERNAME";
export const GET_USERDATA_SUCCESS = "GET_USERDATA_SUCCESS";
export const GET_TABLEDATA_SUCCESS = "GET_TABLEDATA_SUCCESS";
export const DELETE_DATA = "DELETE_DATA";
export const GET_CHANGECHART_VISIBLE = "GET_CHANGECHART_VISIBLE";
