export const USER_LOGIN = "USER_LOGIN";
export const USER_SIGNUP = "USER_SIGNUP";
export const GET_ACCOUNT = "GET_ACCOUNT";

export const GET_CHATHISTORY = "GET_CHATHISTORY";
export const GET_CHATHISTORY_SUCCESS = "GET_CHATHISTORY_SUCCESS";
export const GET_CHATHISTORY_ERROR = "GET_CHATHISTORY_ERROR";

export const GET_HISTORY_SEARCH = "GET_HISTORY_SEARCH";
